### ISSUE TITLE
Short term goals

### ISSUE THREAD

**Issue by tamj0rd2** [tamj0rd2/ModRDN#2]
## Goals

- [x] Get the existing maps working with the mod
- [ ] Be able to spawn hench from lab
- [ ] Be able to collect coal
- [ ] Be able to build structures
- [ ] Be able to collect elec
- [ ] Be able to spawn units

## TODOs

- [ ] Add script to package files up into a zip file
- [ ] Add a script to create SGA from mod folder (dunno if it's even possible). Once it's done, add it to the install-assets script

**Comment by tamj0rd2** [comment]
# Busting bugs

- Replace all references to **`dbreak`** with `dbfatalf`. Anywhere UNREF_P is used without any implementation should also call dbfatalf.

**Comment by tamj0rd2** [comment]
Keywords to check collision/im[ass issue:

OBB
OnSpawnEntity
Pathfinding
EntityDynamics
DoSpawnEntity
AddEntityPathfinding
SpawnEntity
AddEntity
DoSpawnEntity

SetUnderConstruction
Construction
CantBuild
AddWorldEntities
EntityInSpawning

**Comment by tamj0rd2** [comment]
CanPlaceBuildingImpass might come in handy
